stages:
  - build-shaders
  - build
  - build-release
  - test

.setup-glslc:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1
  tags:
    - vulkan
  before_script:
    - docker build --rm -t shaderc/shaderc -f shaderc/Dockerfile shaderc

build-shaders:
  stage: build-shaders
  tags:
    - vulkan
  extends: .setup-glslc
  script:
    - ./compile_shaders.sh
  artifacts:
    paths:
      - assets/shaders/*.spv

rust-vulkan-build:
  tags:
    - rust
    - vulkan
  stage: build
  dependencies: 
    - build-shaders
  before_script:
    - rustc --version && cargo --version
    - cargo clean
  script:
    - ls -la assets/shaders
    - cargo build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_ID-debug"
    paths:
      - target/debug/vulkan-tutorial
    expire_in: 1 week

rust-vulkan-build-release:
  tags:
    - rust
    - vulkan
  stage: build-release
  dependencies: 
    - build-shaders
  before_script:
    - rustc --version && cargo --version
    - cargo clean
  script:
    - cargo build --release
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_ID-release"
    paths:
      - target/release/vulkan-tutorial
  rules:
    - if: $CI_COMMIT_TAG

# Use cargo to test the project
test:cargo:
  tags:
    - rust
    - vulkan
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
