stages:
  - build
  - test

image: "rust:latest"

rust-vulkan-build:
  tags:
    - rust
    - vulkan
  stage: build
  before_script:
    - cargo clean
  script:
    - cargo build

# Use cargo to test the project
test:cargo:
  tags:
    - rust
    - vulkan
  stage: test
  image: "rust:latest"
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose