stages:
  - build
  - build-release
  - test

.setup-glslc:
  tags:
    - vulkan
  before_script:
    - rustc --version && cargo --version
    - cargo clean
    - git clone --depth 1 --branch v2022.4 https://github.com/google/shaderc
    - cd shaderc
    - docker build --rm -t shaderc/shaderc .

rust-vulkan-build:
  tags:
    - rust
    - vulkan
  stage: build
  extends: .setup-glslc
  script:
    - docker run --rm shaderc/shaderc glslc --version
    - cargo build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_ID-debug"
    paths:
      - target/debug/vulkan-tutorial
    expire_in: 1 week

rust-vulkan-build-release:
  tags:
    - rust
    - vulkan
  stage: build-release
  extends: .setup-glslc
  script:
    - cargo build --release
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_ID-release"
    paths:
      - target/release/vulkan-tutorial
  rules:
    - if: $CI_COMMIT_TAG

# Use cargo to test the project
test:cargo:
  tags:
    - rust
    - vulkan
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
